name: tourism_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  sqflite: ^2.4.2

  http: ^1.5.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSansCondensed
      fonts:
        - asset: assets/fonts/IBMPlexSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansCondensed-Thin.ttf
          weight: 100
